apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-kampusreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-kampusreport
  template:
    metadata:
      labels:
        app: db-kampusreport
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-kampusreport-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-kampusreport-configmap
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-kampusreport-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-kampusreport-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-kampusreport-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-kampusreport-data
          persistentVolumeClaim:
            claimName: db-kampusreport-pvc

