apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      index index.php index.html;
      error_log  /var/log/nginx/error.log debug;  # Increased log level for debugging
      access_log /var/log/nginx/access.log;
      root /var/www/kampus_report/public;
      
      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass app-kampusreport-service:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          
          # Added debugging headers
          add_header X-Debug-Message "Processing PHP through FPM" always;
          
          # Increased timeouts
          fastcgi_read_timeout 300;
          fastcgi_connect_timeout 300;
          fastcgi_send_timeout 300;
          
          # Additional parameters
          fastcgi_intercept_errors on;
          fastcgi_buffer_size 16k;
          fastcgi_buffers 4 16k;
      }
      
      location / {
          try_files $uri $uri/ /index.php?$query_string;
          gzip_static on;
      }
    }